import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import SigninDialog from "@/features/auth/components/SigninDialog";
import SignupDialog from "@/features/auth/components/SignupDialog";
import { cn } from "@/lib/utils";
import { themeInitScript } from "@/themes/theme-init-script";
import MainFooter from "@/widgets/MainFooter";
import MainHeader from "@/widgets/MainHeader";

import "../themes/globals.css";
import "../themes/transition.css";

import { AppProviders } from "@/providers/AppProviders";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			suppressHydrationWarning
			lang="en"
			className={cn(
				"h-full",
				"antialiased",
				geistSans.variable,
				geistMono.variable,
				"font-sans",
				inter.variable,
			)}
		>
			<head>
				<script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
			</head>
			<body className="min-h-full flex flex-col">
				<AppProviders>
					<MainHeader />
					<main className="main-layout flex-1">{children}</main>
					<MainFooter />
					<SigninDialog />
					<SignupDialog />
				</AppProviders>
			</body>
		</html>
	);
}
